sudo: required
dist: trusty
services:
  - docker
language: python
install:
  - docker build -t container .
script:
  - docker run --name cont -p 6311:6311 -d container
  - docker ps | grep -q cont
after_success:
  - sudo apt-get install -y curl
  - source trigger_docker_build.sh
